---
- hosts: docker 
  become: true
  tasks:

    - name: install
      apt:
        name: "{{item}}" #var which takes the name of loop items below
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: grab docker gpg key #get Docker's public key for Docker SW repo
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present

    - name: add docker repo to your apt #add Docker repo to Ubuntu so we can install their SW
        apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu bionic stable
          state: present

    - name: install docker #install docker items from the loop below 
        apt:
          name: "{{item}}"
          state: latest
          update_cache: yes
        loop:
          - docker-ce     #containerengine
          - docker-ce-cli #cmd line interface
          - containerd.io #container runtime

  handlers:
    - name: restart docker
      service: 
        name: docker 
        state: restarted