version: '3' 

services:

  frontend:
    build: ./frontend 

  backend:
    build: ./backend 

  live-reloader:
    image: apogiatzis/livereloading
    container_name: livereloader
    privileged: true
    environment:
      - RELOAD_DELAY=1              # seconds
      - RELOAD_CONTAINER=weatherapp-backend-1
      - RELOAD_CONTAINER=weatherapp-frontend-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "weatherapp:/var/lib/docker/volumes/weatherapp_data"

